site_name: Crazyflow Documentation
site_description: Fast, parallelizable simulations of Crazyflies in JAX
site_url: https://utiasdsl.github.io/crazyflow/
repo_name: utiasDSL/crazyflow
repo_url: https://github.com/utiasDSL/crazyflow

theme:
  name: material
  logo: img/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [../crazyflow]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/utiasDSL/crazyflow

extra_css:
  - stylesheets/extra.css
